### ISSUE TITLE
Kotlin Gradle plugin version buidl failure

### ISSUE THREAD

**Issue by abd0ibrahim** [thyagoluciano/flutter_launch#17]
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_launch' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
Please Update Kotlin gradle plugin, I had to do it manually in your gradle file

**Comment by bdairy** [comment]
Same problem here,,, Spend more than a week thought it was flutter issue.... Please fix,, thanks

**Comment by abd0ibrahim** [comment]
@bdairy If you are using Android Studio select project directory filter > External Libraries > Flutter Plugins > Flutter_launch > android > build.gradle
You can also find it in flutter installation folder C:\flutter\.pub-cache\hosted\pub.dartlang.org\

**Comment by bdairy** [comment]
@abd0ibrahim  thanks a lot,, I managed,,,... If this is not being updated we should find an alternate.. don't u agree?

**Comment by abd0ibrahim** [comment]
@bdairy Yes, I actually faced this problem when trying to continuous integration build so I changed to [flutter_open_whatsapp](https://pub.dev/packages/flutter_open_whatsapp) seems like the same implementation without major differences

**Comment by ReyzalH** [comment]
i use this one in my pubspec.yaml

 flutter_launch:
    git:
      url: git://github.com/thyagoluciano/flutter_launch_whatsapp.git
