### ISSUE TITLE
project ':flutter_launch' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

### ISSUE THREAD

**Issue by JAYTARPARA** [thyagoluciano/flutter_launch#23]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_launch' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Picked up _JAVA_OPTIONS: -Xmx1024M

**MY KOTLIN VERSION IS 1.3.50**

**Comment by MarceloRab** [comment]
I went to External Libraries / Flutter Plugins / flutter_launch / android / build.gradle and changed ext.kotlin_version to 1.3.61.

It looks like this: ext.kotlin_version = '1.3.61'

**Comment by adnankhan74444** [comment]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_launch' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

ext.kotlin_version = '1.3.61' I already have this version but still facing the.
