### ISSUE TITLE
Android Gradle Plugin not supported

### ISSUE THREAD

**Issue by YahyaYousef** [thyagoluciano/flutter_launch#25]
I'm using 1.3.10 gradle 
current use 1.2.71
This error I got 
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
  The following dependencies do not satisfy the required version:
  project ':flutter_launch' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
```

**Comment by iteanjd** [comment]
.

**Comment by redfieldchristabel** [comment]
@YahyaYousef yes you can manually hack the flutter_launch kotlin version to latest. but if you are working with team all of them need to change it . but i will run , credit to https://stackoverflow.com/users/2444546/syeda
